# fly.toml app configuration file generated for fs-blog-list-app-part13 on 2023-07-29T13:51:42+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fs-blog-list-app-part13"
primary_region = "gru"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
