version: '3.8'

services:
  backend:
    image: bloglist-backend-dev
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env

  frontend:
    image: bloglist-frontend-dev
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app

  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "frontend"
      - "backend"
    ports:
      - 8080:80
    container_name: reverse-proxy